name: Build Image
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up AWS Cli
        run: |
          sudo apt update -y
          sudo apt install awscli -y
          aws --version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        run: |
          docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws/$AWS_ECR_ID
        env:
          AWS_ECR_ID: ${{ secrets.AWS_ECR_ID }}
      - name: Build and push image & upload to ECR
        id: build_images
        run: |
          docker build . -t scale-out-backend:latest
          docker tag scale-out-load-tester:latest public.ecr.aws/$AWS_ECR_ID/scale-out-load-tester:latest
          docker push public.ecr.aws/$AWS_ECR_ID/scale-out-load-tester:latest
        env:
          AWS_ECR_ID: ${{ secrets.AWS_ECR_ID }}